### ISSUE TITLE
Broken Document Tree tabs and functionality in 1.2.1 - many .js errors in console

### ISSUE THREAD

**Issue by bschwenk** [modxcms/evolution#1295]
Just updated from Evo 1.0.14 to 1.2.1. Tested locally and all worked fine. Then of course on production, ran into a problem that I can't seem to solve: some Document Tree content shows but is completely broken. The tabs do not work. None of the links work. Everything else in the manager outside of the tree works.

Couple of unique things about server environment:

1. MODx is running on 2 load-balanced web servers. An lsync job syncs files between them. (It was working fine in 1.0.14.)
2. The MODx manager is accessed exclusively via HTTPS.

**Screenshot of problem:**
![manager](https://cloud.githubusercontent.com/assets/8420188/24591297/4cc62c44-17cc-11e7-9e78-8787980d65b4.png)

Here are the errors I'm seeing in the console when I open the Document Tree in a new browser window.

> Navigated to https://www.xxxxxxxxxx.com/manager/
> index.php?a=1&f=tree:1178 Uncaught SyntaxError: Unexpected token <
> index.php?a=1&f=tree:1203 Uncaught ReferenceError: initQuicksearch is not defined
>     at index.php?a=1&f=tree:1203
> (anonymous) @ index.php?a=1&f=tree:1203
> index.php?a=1&f=tree:1224 Uncaught TypeError: treePane.addTabPage is not a function
>     at index.php?a=1&f=tree:1224
> (anonymous) @ index.php?a=1&f=tree:1224
> index.php?a=1&f=tree:1246 Uncaught ReferenceError: initQuicksearch is not defined
>     at index.php?a=1&f=tree:1246
> (anonymous) @ index.php?a=1&f=tree:1246
> index.php?a=1&f=tree:1267 Uncaught TypeError: treePane.addTabPage is not a function
>     at index.php?a=1&f=tree:1267
> (anonymous) @ index.php?a=1&f=tree:1267
> index.php?a=1&f=tree:1517 Uncaught ReferenceError: initQuicksearch is not defined
>     at index.php?a=1&f=tree:1517
> (anonymous) @ index.php?a=1&f=tree:1517
> index.php?a=1&f=tree:1538 Uncaught TypeError: treePane.addTabPage is not a function
>     at index.php?a=1&f=tree:1538
> (anonymous) @ index.php?a=1&f=tree:1538
> index.php?a=1&f=tree:1608 Uncaught ReferenceError: initQuicksearch is not defined
>     at index.php?a=1&f=tree:1608
> (anonymous) @ index.php?a=1&f=tree:1608
> index.php?a=1&f=tree:1629 Uncaught TypeError: treePane.addTabPage is not a function
>     at index.php?a=1&f=tree:1629
> (anonymous) @ index.php?a=1&f=tree:1629
> index.php?a=1&f=tree:1664 Uncaught ReferenceError: initQuicksearch is not defined
>     at index.php?a=1&f=tree:1664
> (anonymous) @ index.php?a=1&f=tree:1664
> index.php?a=1&f=tree:1685 Uncaught TypeError: treePane.addTabPage is not a function
>     at index.php?a=1&f=tree:1685
> (anonymous) @ index.php?a=1&f=tree:1685
> index.php?a=1&f=tree:1694 Uncaught ReferenceError: initQuicksearch is not defined
>     at index.php?a=1&f=tree:1694

MODX Version: 1.2.1
PHP Version: 5.3.3
Database (MySQL, SQL Server, etc) Version: MySQL 5.5.49-37.9-log

**Comment by dmi3yy** [comment]
Tree tabs not work on 1.2+



Отправлено с iPhone

**Comment by Deesen** [comment]
It seems to me these files could not be loaded, maybe in browser-console you can find 404-errors?

- /manager/media/script/tabpane.js
- /manager/media/script/jquery.quicksearch.js

**Comment by bschwenk** [comment]
Hi @Deesen, thanks for the reply. Every resource is being loaded properly:

![resources](https://cloud.githubusercontent.com/assets/8420188/24608396/6831f3aa-1844-11e7-8a3a-a4de6de57c3d.png)
 
Interesting about line 1178...looks like there may be an unclosed script??? Here is the source from 1170 - 1180:
 
            } else {
                // Early FF can, however, use this usual method where IE cannot with secure links.
                window.location = url;
            }
        }
        /////////////////////////////////////////////////////////////
        // Prepare "remember scroll-position" functions
            <div><img src="media/style/MODxRE2/images/tree/sitemap.png" width="16" height="16" align="absmiddle" />&nbsp;<span class="rootNode" onClick="treeAction(event, 0, '[xxxxxxxxxxxx]');"><b>[xxxxxxxxxxxx]</b></span><div id="treeRoot"></div></div>
    </div> 

And here it is in the console which highlights the error:

![source-error](https://cloud.githubusercontent.com/assets/8420188/24608646/6b26affa-1845-11e7-913f-50646f6af8ee.png)

**Comment by bschwenk** [comment]
Interesting -- comparing this to my local installation, there seems to be a big chunk of code missing in the source here. I'll see if I can track this down...

**Comment by bschwenk** [comment]
So, I had an incomplete file in `assets/plugins/elementsintree/assets/txt_content.tpl`. Not sure how that happened, but once I uploaded the full version of the file, everything began working again.
